### ISSUE TITLE
threads leak in thread-per-connection dispatcher plugin

### ISSUE THREAD

**Issue by vlad-lesin** [Percona-Lab/query-playback#2]
When thread-per-connection dispatcher plugin is used each new connection is served by separate thread. In the case if there is no information about connection termination in input file the thread which serves connection will not be finished and the number of spawned threads  and mysql connections will rise. As for tcpdump plugin such situation can be when there is no FIN/RST packet in tcpdump file due to dropped packets during capturing (see https://bugs.launchpad.net/percona-playback/+bug/1034525 ). query-log plugin does not contain the code for detecting connection finishing at all.

The fast workaround: use thread thread-pool dispatcher plugin instead of default thread-per-connection(--dispatcher-plugin=thread-pool).

The possible fixes:
1) check if it is possible to detect connection finishing in query log and implement corresponsing feature in query-log plugin (see "administrator command: Quit" in query log file)
2) set time-to-live for inactive threads in thread-per-connection dispatcher plugin

**Comment by undingen** [comment]
I fixed the leaking connection issue in https://github.com/Percona-Lab/query-playback/pull/23.
I added a preprocessing step which detect the last query of every connection and automatically close the thread afterwards.
