### ISSUE TITLE
Can't complile w/o libdrizzle

### ISSUE THREAD

**Issue by dveeden** [Percona-Lab/query-playback#5]
This doesn't work if libdrizzle-devel is not installed.

```
./configure --disable-libdrizzle
make
```

I think it makes sense to be able to compile it w/o drizzle

**Comment by dveeden** [comment]
On my CentOS 6 system libdrizzle-devel 5.1.4 was installed, which didn't bring /usr/lib64/pkgconfig/libdrizzle.pc
Installing the (older?) libdrizzle-devel-0.6-1.3 from ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/LenzGr/CentOS_CentOS-6/x86_64/libdrizzle-devel-0.6-1.3.x86_64.rpm and libdrizzle0 from the same source made it work.

**Comment by undingen** [comment]
I think this issue can be closed because https://github.com/Percona-Lab/query-playback/pull/6 removed the libdrizzle dependency.

**Comment by dveeden** [comment]
Yes I agree.
