### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by thuey** [Percona-Lab/query-playback#8]
I'm running OSX. I cloned the repo and tried to follow the instructions. When I run make, I get this:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in po
make[2]: *** No rule to make target `all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Running configure again, I see this at the bottom:

```
grep: po/Makefile.in: No such file or directory
config.status: WARNING: po/Makefile.in.in was not created by intltoolize.
```

**Comment by plebedev** [comment]
I was able to build latest master on OSX following the instructions but I had to make few changes: https://github.com/plebedev/query-playback

I also had to install tbb `brew install tbb` and add the following to cmake `-DMYSQL_LIB=<path_to_libmysqlclient.dylib>`

Hope, it helps.
